url: '' #https://y7kim.github.io
baseurl: '' # /agency-jekyll-theme/

# Site settings
title: Ansible for Real Life Automation
email: gini@iamgini.com
description: "A complete Ansible handbook filled with real life IT automation use cases"


# Team names, titles and social links
people:
- name: Kay Garland
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Larry Parker
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Diana Petersen
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
  #   url: https://twitter.com/GiniGangadharan
  #   icon: "fab fa-twitter"
  #- url: https://facebook.com
  #  icon: "fab fa-facebook-f"
  
  - title: linkedin
    url: https://www.linkedin.com/in/gineesh/
    icon: "fab fa-linkedin-in"
  - title: github
    url: https://github.com/ginigangadharan/
    icon: "fab fa-github"
  - title: instagram
    url: https://www.instagram.com/ginigangadharan/
    icon: "fab fa-instagram"
  - title: twitter
    url: https://twitter.com/GiniGangadharan


# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty


# FAQs
faqs:
  - question: Is there a PDF or soft copy available?
    answer: Yes, the book is available in paperback (Hard copy or print) and eBook (PDF, Mobi, Kindly) formats.
  - question: Can I get my book delivered to India?
    answer: "Yes, it also depends on from which site you are ordering. Eg: if you are ordering from Amazon, then follow the Amazon delivery availability."
  - question: Can I learn everything about Ansible by reading this book?
    answer: No, the book is intended for covering the use cases which you can implement with Ansible automation. The book will help you to start learning Ansible, understand how to find the use cases and how to start with real-life automation in your IT environment.

reviews:
  - name: image
